### ISSUE TITLE
I have no idea how to run this, could you please help?

### ISSUE THREAD

**Issue by asanehi** [alii/supreme-monitor#1]
Hey, I've 0 ts knowledge. This seems interesting to build open so could I know how to run and get around this?

**Comment by alii** [comment]
Hi, no worries at all.

First of all, make sure you clone the repo. You can do that by clicking the "Download Zip" button. After downloading make sure you extract the files to another location:

<img width="448" alt="image" src="https://user-images.githubusercontent.com/25351731/119315362-aaec4480-bc6d-11eb-8764-a5b69920cdae.png">

Secondly, you're going to want to ensure you have Node 15+ installed on your computer. You can download it [here](https://nodejs.org/en/download/current/) if not.

After this you will need to make a file with the exact name of `.env` in the location on your computer you extracted the files to. You need to fill in the values as specified in the readme:

```
# Discord bot token
TOKEN=

# Discord channel ID
CHANNEL=
```


After that, run `npm install`, then run `npm run build` and finally `npm start`.
Note: if you use/have yarn installed, then prefer that over npm, since there this project is versioned with yarn
